import { fixtures, type FixtureId, FIXED_CLOCK, FIXTURE_REVISION } from './fixtures.js';
import { BRIDGE_VERSION, postBridge } from './bridge.js';
const A='./assets/';
const img=(n:string,c='',a='')=>`<img ${a?`data-anchor="${a}"`:''} class="${c}" data-canonical-asset="${n}" src="${A}${n}" alt="">`;
const fixture=()=>{const q=new URLSearchParams(location.search).get('fixture') as FixtureId|null;return q&&q in fixtures?q:'session-prestart'};
const header=(title:string,sub:string)=>`<header>${img('001_logo_ose.png','logo','header_logo')}<h1 data-anchor="header_title">${title}</h1><p class="sub" data-anchor="header_subtitle">${sub}</p><button class="menu" data-anchor="menu">${img('002_icone_menu.png')}</button><button class="settings" data-anchor="settings">${img('003_icone_configuracoes.png')}</button></header><i class="header-line" data-axis="header_divider"></i>`;
const nav=()=>`<nav data-axis="bottom_nav"><button data-anchor="bottom_session" class="sel">${img('006_icone_pergaminho.png')}<small>SESSÃO</small></button><button data-anchor="bottom_map">${img('013_icone_mapa.png')}<small>MAPA</small></button><button data-anchor="bottom_sheet">${img('012_icone_livros.png')}<small>FICHA</small></button><button data-anchor="bottom_bag">${img('015_icone_mochila.png')}<small>BOLSA</small></button></nav>`;
const rail=(n:string,l:string,a:string)=>`<button class="rail" data-slot="${a}">${img(n,'',a)}<small>${l}</small></button>`;
function prestart(){return `<main class="screen prestart">${header('NOVA SESSÃO','SESSION_PRESTART · narrativa ainda não iniciada')}<section class="ready">${img('006_icone_pergaminho.png','ready-icon','ready_icon')}<h2 data-anchor="ready_title">PRONTO PARA COMEÇAR</h2><p data-anchor="ready_subtitle">Party e posição inicial definidas.</p></section><section class="prep" data-anchor="prep_panel">${img('075_painel_pergaminho_rustico.png','bg')}<div><b>PREPARAÇÃO DA SESSÃO</b><label>POSIÇÃO INICIAL</label><p>Entrada das Cavernas</p><label>PARTY</label><p>4 aventureiros • pronta</p><label>ESTADO</label><p>Narrativa ainda não iniciada</p><small>PLAYER_ACTION permanece indisponível.<br>Nenhum tempo, posição, NPC ou<br>consequência mecânica avançou.</small></div></section><aside>${rail('014_icone_grupo.png','PARTY','rail_party')}${rail('013_icone_mapa.png','MAPA','rail_map')}${rail('011_icone_d20.png','DADOS','rail_dice')}${rail('015_icone_mochila.png','BOLSA','rail_bag')}</aside><button class="cta" data-anchor="start_cta">${img('OSE_GLOBAL_A202_botao_base_ativo_sem_texto.png')}<span>COMEÇAR A NARRAR</span></button><button class="pa-pre" data-anchor="player_action" disabled>${img('OSE_GLOBAL_A201_botao_base_neutro_sem_texto.png')}<span>PLAYER_ACTION</span></button><small class="pa-note">indisponível</small><button class="tts-pre" data-anchor="tts_control" disabled>${img('OSE_SESSION_NEW_A701_icone_tts_ouvir.png')}</button><button class="gm-pre" data-anchor="gm_help">${img('OSE_GLOBAL_A201_botao_base_neutro_sem_texto.png')}<span>GM_HELP</span></button><small class="gm-note">não avança mundo</small><i class="tts-line" data-axis="tts_divider"></i><p class="tts-note"><b>TTS</b>　 indisponível até existir narração.</p>${nav()}</main>`}
function active(keyboard=false){const f=fixtures['session-active'];return `<main class="screen active ${keyboard?'kbd-open':''}">${header('CRIPTA SOB O OUTEIRO','SESSION_ACTIVE · narrativa em andamento')}<section class="status"><div data-anchor="status_light">${img('008_status_tocha_30m.png')}</div><div data-anchor="status_move">${img('010_status_movimento_90.png')}</div><div data-anchor="status_dice">${img('011_icone_d20.png')}</div><div data-anchor="status_party">${img('014_icone_grupo.png')}</div></section><section class="narr" data-anchor="narration_panel">${img('OSE_SESSION_A502_frame_narracao_flexivel.png','bg')}<div><b>MESTRE</b><p>${f.narrative}</p></div></section><button class="tts" data-slot="tts_control">${img('OSE_SESSION_NEW_A701_icone_tts_ouvir.png','', 'tts_control')}<small>OUVIR<br>TTS</small></button><h2 class="action-title">AÇÃO / PLAYER_ACTION</h2><label class="what">O que você faz?</label><i class="action-line"></i><small class="action-hint">Texto do jogador...</small><section class="action" data-anchor="player_action_panel">${img('072_painel_pergaminho_pautado.png','bg')}<textarea id="playerAction" aria-label="PLAYER_ACTION">${keyboard?'Examino a porta sem abri-la.':''}</textarea></section><button class="send" data-anchor="send_button">${img('OSE_GLOBAL_A202_botao_base_ativo_sem_texto.png')}<span>ENVIAR</span></button><button class="gm" data-anchor="gm_help">${img('OSE_GLOBAL_A201_botao_base_neutro_sem_texto.png')}<span>GM_HELP</span></button><small class="active-gm-note">não avança mundo</small><section class="shortcuts">${rail('013_icone_mapa.png','MAPA','shortcut_map')}${rail('012_icone_livros.png','FICHA','shortcut_sheet')}${rail('011_icone_d20.png','DADOS','shortcut_dice')}${rail('015_icone_mochila.png','BOLSA','shortcut_bag')}</section><i class="history-line" data-axis="history_divider"></i><section class="history"><h2 data-anchor="history_title">HISTÓRICO DA SESSÃO</h2><p>A narração continua em rolagem vertical. Entradas anteriores permanecem acessíveis sem empurrar PLAYER_ACTION e GM_HELP para o mesmo canal. O concept demonstra conteúdo extenso sem transformar a tela em comprimento padrão.</p></section>${nav()}</main>${keyboard?keyboardMarkup():''}`}
function keyboardMarkup(){return `<div class="keyboard-sim">${['QWERTYUIOP','ASDFGHJKL','ZXCVBNM'].map(r=>`<div>${[...r].map(k=>`<span>${k}</span>`).join('')}</div>`).join('')}<em>espaço</em></div>`}
function overlay(id:FixtureId){const mode=new URLSearchParams(location.search).get('conceptOverlay')||'0';if(mode==='0')return'';const n=id==='session-active'?'CONCEPT_SESSION_ACTIVE_415x915.png':'CONCEPT_SESSION_PRESTART_415x915.png';const opacity=mode==='concept'?'1':mode==='dom'?'0':'0.5';return `<div id="conceptOverlay" class="overlay" data-overlay-mode="${mode}" style="opacity:${opacity}"><img src="${A}${n}" alt="concept"></div>`}
const id=fixture();document.documentElement.dataset.clock=FIXED_CLOCK;document.body.innerHTML=(id==='session-prestart'?prestart():active(id==='keyboard-open'))+overlay(id);document.body.dataset.ready='true';postBridge({version:BRIDGE_VERSION,type:'ViewState',payload:{fixture:id,fixtureRevision:FIXTURE_REVISION,clock:FIXED_CLOCK}});