import {test,expect} from '@playwright/test';
import {mkdirSync} from 'node:fs';import path from 'node:path';
mkdirSync(path.resolve('captures'),{recursive:true});
const screens=[['session','active'],['session','encounter'],['session','combat'],['session','recovery'],['map','active'],['sheet','active'],['company','active']] as const;
const stabilize=async(page:any)=>{
  await page.addStyleTag({content:'*{animation:none!important;transition:none!important;caret-color:transparent!important} html{scroll-behavior:auto!important}'});
  await page.evaluate(()=>Promise.all([document.fonts.ready,...Array.from(document.images).map((i:any)=>i.decode?i.decode().catch(()=>null):Promise.resolve())]));
  await page.waitForTimeout(350);
};
for(const [screen,state] of screens){test(`${screen}-${state} 415x915 approved P1 shell`,async({page})=>{const failed:string[]=[];page.on('requestfailed',r=>failed.push(r.url()));await page.goto(`/?screen=${screen}&state=${state}`);await page.waitForLoadState('networkidle');await stabilize(page);expect(await page.evaluate(()=>[innerWidth,innerHeight])).toEqual([415,915]);expect(await page.locator('#device').getAttribute('data-screen')).toBe(screen);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=415&&document.documentElement.scrollHeight<=915)).toBeTruthy();const bad=await page.locator('img:visible').evaluateAll((xs:HTMLImageElement[])=>xs.filter(x=>!x.complete||x.naturalWidth<1).map(x=>x.src));expect(bad).toEqual([]);expect(failed).toEqual([]);if(screen==='session'){await expect(page.locator('[data-channel="PLAYER_REACTION"]')).toHaveCount(1);await expect(page.locator('.gm-help')).toBeVisible();}if(screen==='map'){await expect(page.locator('[data-geometry-version="1"]')).toHaveCount(2);await expect(page.locator('[data-direct-movement="forbidden"]')).toHaveCount(1);}await page.screenshot({path:path.resolve(`captures/P1_${screen.toUpperCase()}_${state.toUpperCase()}_415x915.png`),animations:'disabled'});});}
test('preview reaction and GM_HELP do not mutate locally without native bridge',async({page})=>{await page.goto('/?screen=session&state=active');await stabilize(page);await page.locator('#reaction').fill('descansar');await page.locator('.send-reaction').click();await expect(page.locator('#toast')).toContainText('preview');await page.locator('.gm-help').click();await expect(page.locator('#toast')).toContainText('GM_HELP');});
